export const amstudsData = {
  chapters: [
    { id: "all", label: "All", title: "Full Review" },
    { id: "cold-war", label: "Cold War", title: "The Cold War" },
    { id: "affluent-society", label: "Affluent Society", title: "An Affluent Society" },
    { id: "civil-rights", label: "Civil Rights", title: "Civil Rights Movement" },
    { id: "vietnam", label: "Vietnam", title: "The Vietnam War" },
    { id: "nixon", label: "Nixon", title: "Nixon & Conservative Turn" },
  ],
  modes: [
    { id: "overview", label: "Overview" },
    { id: "term-ids", label: "Term IDs" },
    { id: "flashcards", label: "Flashcards" },
    { id: "quiz", label: "MCQ" },
    { id: "free-response", label: "Free Response" },
    { id: "matching", label: "Matching" },
    { id: "cram", label: "Cram Sheet" },
    { id: "review-mistakes", label: "Review Mistakes" },
  ],

  // === TERM IDs — the main study mode ===
  termIds: [
    // ── Cold War ──
    { term: "Iron Curtain", definition: "Churchill's metaphor (1946 speech) for the dividing line between Soviet-controlled Eastern Europe and the democratic West. 'From Stettin in the Baltic to Trieste in the Adriatic.'", unit: "cold-war", tag: "Cold War" },
    { term: "Containment", definition: "US foreign policy strategy originating from George Kennan's Long Telegram — stop the spread of Soviet communism by all means short of direct war. Shaped decades of policy.", unit: "cold-war", tag: "Cold War" },
    { term: "Long Telegram (1946)", definition: "George Kennan's 8,000-word cable to the State Department explaining Soviet hostility and recommending containment. Argued Soviets believed there could be no permanent peace with the US.", unit: "cold-war", tag: "Cold War" },
    { term: "Truman Doctrine (1947)", definition: "Policy declaring the US would support free peoples resisting subjugation by armed minorities or outside pressure. Gave $400 million in aid to Greece and Turkey to prevent communist takeover.", unit: "cold-war", tag: "Cold War" },
    { term: "Marshall Plan (1947)", definition: "US program of massive economic aid to rebuild war-torn Western Europe. Aimed to prevent communist influence by alleviating poverty and instability that bred totalitarianism.", unit: "cold-war", tag: "Cold War" },
    { term: "NATO (1948)", definition: "North Atlantic Treaty Organization — mutual defense alliance between US, Canada, and Western European nations. An attack on one member is considered an attack on all.", unit: "cold-war", tag: "Cold War" },
    { term: "Warsaw Pact", definition: "Soviet-led military alliance of Eastern European communist nations, formed as a counterpart to NATO. Created a formal two-bloc division of Europe.", unit: "cold-war", tag: "Cold War" },
    { term: "Berlin Airlift (1948-49)", definition: "US and British operation to fly supplies into West Berlin after the Soviet Union blockaded all ground routes. Demonstrated Western resolve without direct military confrontation.", unit: "cold-war", tag: "Cold War" },
    { term: "NSC-68 (1950)", definition: "National Security Council Report calling for massive US military buildup to counter Soviet threat. Warned Soviets would have atomic capability within four years and recommended increased defense spending.", unit: "cold-war", tag: "Cold War" },
    { term: "Domino Theory", definition: "Belief that if one country fell to communism, neighboring countries would follow like dominoes. Used to justify US intervention in Korea and Vietnam.", unit: "cold-war", tag: "Cold War" },
    { term: "Red Scare / McCarthyism", definition: "Period of intense anti-communist paranoia in the US. Senator McCarthy led investigations, loyalty oaths were required, and people were blacklisted based on suspected communist ties.", unit: "cold-war", tag: "Cold War" },
    { term: "Duck and Cover", definition: "Civil defense campaign teaching Americans (especially children) to protect themselves from nuclear attack. Reflects the atomic anxiety of the Cold War era.", unit: "cold-war", tag: "Cold War" },
    { term: "Détente", definition: "Policy of easing Cold War tensions, especially under Nixon. Included diplomatic openings to China and arms limitation talks with the USSR.", unit: "cold-war", tag: "Cold War" },

    // ── Affluent Society ──
    { term: "Levittown", definition: "Mass-produced suburban housing development built by William Levitt starting in 1951. Affordable homes ($8,990-$16,500) but racially exclusionary — no homes were sold to Black families.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "Kitchen Debate (1959)", definition: "Televised exchange between VP Nixon and Soviet Premier Khrushchev at a model American kitchen in Moscow. Nixon argued American consumer goods proved capitalism's superiority.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "Baby Boom", definition: "Massive population explosion after WWII as returning soldiers started families. Drove suburbanization, school construction, and consumer demand.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "Suburbanization", definition: "Mass migration of Americans from cities to suburbs in the 1950s, enabled by the GI Bill, highway construction, and affordable housing like Levittown.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "GI Bill", definition: "Provided WWII veterans with college tuition, low-cost home loans, and job training. Fueled the growth of the middle class and suburbs, but benefits were unequally distributed by race.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "Consumer Culture", definition: "1950s emphasis on purchasing goods — cars, TVs, appliances — as a measure of success, freedom, and American identity. Tied to Cold War competition with the USSR.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "The Affluent Society (Galbraith, 1958)", definition: "Book by John Kenneth Galbraith criticizing America's prioritization of private wealth over public services. Argued the productive society's problem was its uneven distribution of prosperity.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "The Other America (Harrington, 1962)", definition: "Book exposing the 40-50 million Americans living in poverty, invisible beneath suburban prosperity. Argued the poor were 'increasingly isolated from contact with, or sight of, anybody else.'", unit: "affluent-society", tag: "Affluent Society" },
    { term: "Beat Generation", definition: "Literary and cultural movement (Allen Ginsberg, Jack Kerouac) rejecting 1950s conformity and materialism. Ginsberg's poem 'America' directly challenged Cold War society.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "Conformity (1950s)", definition: "Social pressure to fit into the suburban, consumer-driven, nuclear family ideal. Television shows like Ozzie and Harriet reinforced these norms.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "The Green Book", definition: "Travel guide listing safe businesses, hotels, and restaurants for African Americans during the Jim Crow era. Necessary because of widespread discrimination and danger while traveling.", unit: "affluent-society", tag: "Affluent Society" },
    { term: "Mass Culture", definition: "Spread of television, advertising, and standardized entertainment in the 1950s. By decade's end, the nation had 144 million people and TV had transformed daily life.", unit: "affluent-society", tag: "Affluent Society" },

    // ── Civil Rights ──
    { term: "Plessy v. Ferguson (1896)", definition: "Supreme Court ruling that 'separate but equal' facilities did not violate the 14th Amendment. Legalized segregation for nearly 60 years until overturned by Brown v. Board.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "De jure segregation", definition: "Segregation enforced by law, common in the South. Laws forbade African Americans from attending the same churches, pools, restaurants, or marrying white people.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "De facto segregation", definition: "Segregation by practice and custom without explicit laws, common in the North. Housing discrimination kept neighborhoods racially divided.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Jim Crow Laws", definition: "State and local laws enforcing racial segregation in the Southern US from the 1870s through the 1960s. Covered everything from schools to drinking fountains.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Executive Order 9981 (1948)", definition: "Truman's order officially desegregating the US military. Influenced by civil rights activist A. Philip Randolph, who threatened a march on Washington.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Brown v. Board of Education (1954)", definition: "Supreme Court ruling that 'separate educational facilities are inherently unequal,' overturning Plessy. Brown II ordered desegregation 'with all deliberate speed' — which allowed very slow implementation.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Emmett Till (1955)", definition: "14-year-old Black boy from Chicago murdered in Money, Mississippi for allegedly violating racial boundaries. His mother's decision to hold an open-casket funeral galvanized the civil rights movement.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Montgomery Bus Boycott (1955-56)", definition: "Year-long boycott of Montgomery, Alabama buses sparked by Rosa Parks' arrest. Led by MLK Jr. and the SCLC; ended when the Supreme Court declared bus segregation unconstitutional.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Little Rock Nine (1957)", definition: "Nine Black students who enrolled at Little Rock Central High School in Arkansas. Governor Orval Faubus blocked them; President Eisenhower sent the 101st Airborne to protect them.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "NAACP", definition: "National Association for the Advancement of Colored People. Founded by W.E.B. DuBois and Ida Wells among others. Used legal action to fight racial discrimination.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "CORE", definition: "Congress of Racial Equality. Founded by James Farmer, George Houser, Homer Jack, and Bayard Rustin. Organized Freedom Rides and other direct-action protests.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "SNCC", definition: "Student Non-Violent Coordinating Committee. Associated with Ella Baker. Organized sit-ins and voter registration drives; became more militant over time.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "SCLC", definition: "Southern Christian Leadership Conference. Led by Martin Luther King Jr. and Ralph Abernathy. Organized major campaigns including the Montgomery Bus Boycott and Birmingham.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Civil Disobedience", definition: "Nonviolent resistance to unjust laws. Civil rights leaders were influenced by Mohandas Gandhi and Henry David Thoreau. Included boycotts, sit-ins, and marches.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Sit-ins", definition: "Form of protest where activists sat at segregated lunch counters and refused to leave. Spread rapidly across the South starting with the Greensboro sit-ins in 1960.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Freedom Riders", definition: "Civil rights activists who rode interstate buses into the segregated South to test Supreme Court desegregation rulings. Faced violent opposition.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Letter from Birmingham Jail (1963)", definition: "MLK's letter defending civil disobedience and criticizing white moderates who preferred 'order' over justice. Argued 'injustice anywhere is a threat to justice everywhere.'", unit: "civil-rights", tag: "Civil Rights" },
    { term: "March on Washington (1963)", definition: "Massive demonstration in Washington D.C. where MLK delivered his 'I Have a Dream' speech. Over 250,000 people attended.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Civil Rights Act of 1964", definition: "Federal law banning discrimination based on race, color, religion, sex, or national origin in employment and public accommodations.", unit: "civil-rights", tag: "Civil Rights" },
    { term: "Voting Rights Act of 1965", definition: "Federal law eliminating literacy tests and other barriers used to prevent African Americans from voting. Authorized federal oversight of elections in the South.", unit: "civil-rights", tag: "Civil Rights" },

    // ── Vietnam War ──
    { term: "Ho Chi Minh", definition: "Vietnamese communist leader who declared independence in 1945, referencing the US Declaration of Independence. Led North Vietnam's fight against French colonialism and then the US.", unit: "vietnam", tag: "Vietnam" },
    { term: "Battle of Dien Bien Phu (1954)", definition: "Decisive battle where Vietnamese forces defeated the French, ending French colonial rule in Indochina. Led directly to the Geneva Accords.", unit: "vietnam", tag: "Vietnam" },
    { term: "Geneva Accords (1954)", definition: "Agreement creating a ceasefire and temporarily dividing Vietnam at the 17th parallel. Promised reunification elections that were never held.", unit: "vietnam", tag: "Vietnam" },
    { term: "Gulf of Tonkin Resolution (1964)", definition: "Congressional resolution giving the President unlimited authority to use military force in Vietnam after alleged attacks on US destroyers. Later revealed as exaggerated/fabricated.", unit: "vietnam", tag: "Vietnam" },
    { term: "Operation Rolling Thunder (1965)", definition: "Sustained US bombing campaign against North Vietnam beginning in March 1965. Marked major escalation of US military involvement.", unit: "vietnam", tag: "Vietnam" },
    { term: "Viet Cong (NLF)", definition: "National Liberation Front — communist guerrilla forces fighting in South Vietnam. Established December 1960. Used guerrilla tactics and knowledge of local terrain.", unit: "vietnam", tag: "Vietnam" },
    { term: "Tet Offensive (1968)", definition: "Surprise attacks by North Vietnam and Viet Cong during the Tet holiday. Military failure for the communists but major turning point — shattered US claims the war was being won.", unit: "vietnam", tag: "Vietnam" },
    { term: "Vietnamization", definition: "Nixon's policy of gradually withdrawing US troops while transferring combat responsibility to South Vietnamese forces. Also ended the draft to reduce protests.", unit: "vietnam", tag: "Vietnam" },
    { term: "Ho Chi Minh Trail", definition: "Network of supply routes from North Vietnam through Laos and Cambodia to South Vietnam. Nixon secretly bombed it, turning Cambodia communist.", unit: "vietnam", tag: "Vietnam" },
    { term: "Pentagon Papers (1971)", definition: "Secret government study leaked by Daniel Ellsberg showing the government had systematically misled the public about Vietnam. Deepened the credibility gap.", unit: "vietnam", tag: "Vietnam" },
    { term: "War Powers Act (1973)", definition: "Law requiring the president to inform Congress within 48 hours of deploying troops. Set a 90-day maximum deployment without Congressional approval.", unit: "vietnam", tag: "Vietnam" },
    { term: "Counterculture", definition: "1960s movement opposing mainstream values — anti-war protests, hippie culture, rock music. Artists like Bob Dylan and Country Joe McDonald used music to protest the war.", unit: "vietnam", tag: "Vietnam" },
    { term: "Credibility Gap", definition: "Growing public distrust of government statements about the war's progress. Widened dramatically after the Tet Offensive contradicted official optimism.", unit: "vietnam", tag: "Vietnam" },
    { term: "Agent Orange / Napalm", definition: "Chemical weapons used by US military in Vietnam. Agent Orange was a defoliant causing lasting health damage; napalm was an incendiary weapon. Both caused massive civilian suffering.", unit: "vietnam", tag: "Vietnam" },
    { term: "Draft (Selective Service)", definition: "Mandatory military conscription. Disproportionately affected poor and minority Americans since wealthy could get deferments. Abolished after Vietnam.", unit: "vietnam", tag: "Vietnam" },

    // ── Nixon & Conservative Turn ──
    { term: "Silent Majority", definition: "Nixon's term for the large group of Americans who supported the war and traditional values but didn't protest or demonstrate. Used in his November 1969 speech.", unit: "nixon", tag: "Nixon" },
    { term: "Southern Strategy", definition: "Republican strategy to win Southern white voters by appealing to racial anxieties. Kevin Phillips openly described it: win white voters as Black voters registered as Democrats.", unit: "nixon", tag: "Nixon" },
    { term: "Watergate Scandal", definition: "1972 break-in at Democratic National Committee headquarters and Nixon's subsequent cover-up. Led to Nixon's resignation in August 1974 — the only presidential resignation in US history.", unit: "nixon", tag: "Nixon" },
    { term: "Stagflation", definition: "Combination of economic stagnation, high unemployment, and rising inflation during the 1970s. Consumer prices nearly doubled between 1968 and 1975.", unit: "nixon", tag: "Nixon" },
    { term: "Young Americans for Freedom (YAF)", definition: "Conservative youth organization founded in 1960 in response to counterculture radicalism. Issued the Sharon Statement advocating free markets, limited government, and anti-communism.", unit: "nixon", tag: "Nixon" },
    { term: "Sharon Statement (1960)", definition: "YAF's founding document declaring belief in individual liberty, free market economics, limited government, and the Constitution. Represented the emerging conservative movement.", unit: "nixon", tag: "Nixon" },
    { term: "The Feminine Mystique (Friedan, 1963)", definition: "Betty Friedan's book identifying 'the problem that has no name' — women's dissatisfaction with being confined to homemaker roles. Helped launch second-wave feminism.", unit: "nixon", tag: "Nixon" },
    { term: "National Organization for Women (NOW)", definition: "Founded to champion women's rights and fight gender discrimination. Pushed for the Equal Rights Amendment and workplace equality.", unit: "nixon", tag: "Nixon" },
    { term: "Equal Rights Amendment (ERA)", definition: "Proposed constitutional amendment guaranteeing equal rights regardless of sex. Passed Congress but failed to be ratified by enough states. Phyllis Schlafly led opposition.", unit: "nixon", tag: "Nixon" },
    { term: "Stonewall Riots (1969)", definition: "Police raid on the Stonewall Inn in Greenwich Village, NYC sparked 5 days of rioting. Launched the modern gay rights movement and the tradition of pride marches.", unit: "nixon", tag: "Nixon" },
    { term: "Rachel Carson / Silent Spring (1962)", definition: "Book exposing the dangers of pesticides like DDT to the environment and human health. Helped launch the modern environmental movement.", unit: "nixon", tag: "Nixon" },
    { term: "American Indian Movement (AIM, 1968)", definition: "Organization advocating for Native American rights, modeled after the civil rights movement. Used collective action including the Occupation of Alcatraz (1969).", unit: "nixon", tag: "Nixon" },
    { term: "Cesar Chavez / United Farm Workers", definition: "Organized Latino farmworkers in California for labor union contracts and better working conditions. Part of the broader Chicano movement modeled after Black Power.", unit: "nixon", tag: "Nixon" },
    { term: "Nixon's Détente", definition: "Nixon's policy of easing Cold War tensions — opened diplomatic relations with China and negotiated arms limitations with the USSR. A major shift from rigid confrontation.", unit: "nixon", tag: "Nixon" },

    // ── SCOTUS Cases ──
    { term: "Engel v. Vitale (1962)", definition: "Supreme Court ruled that mandatory prayer in public schools violates the 1st Amendment's establishment clause. Further established separation of church and state.", unit: "civil-rights", tag: "SCOTUS" },
    { term: "Baker v. Carr (1962)", definition: "Supreme Court ruled that federal courts can intervene in redistricting cases under the 14th Amendment's Equal Protection clause. Established 'one person, one vote.'", unit: "civil-rights", tag: "SCOTUS" },
    { term: "Griswold v. Connecticut (1965)", definition: "Supreme Court ruled that the Constitution protects a right to privacy, specifically regarding birth control and contraception. Based on several amendments.", unit: "civil-rights", tag: "SCOTUS" },
    { term: "Miranda v. Arizona (1966)", definition: "Supreme Court ruled that accused persons must be informed of their rights (right to remain silent, right to an attorney) upon arrest. 5th Amendment.", unit: "civil-rights", tag: "SCOTUS" },
    { term: "New York Times v. Sullivan (1964)", definition: "Supreme Court ruled that public officials must prove 'actual malice' to win libel cases, strengthening freedom of the press. 1st Amendment.", unit: "civil-rights", tag: "SCOTUS" },
    { term: "Loving v. Virginia (1967)", definition: "Supreme Court struck down all state bans on interracial marriage as violations of the 14th Amendment's Equal Protection and Due Process clauses.", unit: "civil-rights", tag: "SCOTUS" },
    { term: "Tinker v. Des Moines (1969)", definition: "Supreme Court ruled that students do not 'shed their constitutional rights to freedom of speech or expression at the schoolhouse gate.' 1st Amendment.", unit: "civil-rights", tag: "SCOTUS" },
    { term: "Roe v. Wade (1973)", definition: "Supreme Court ruled that the Constitution protects a woman's right to abortion under the 14th Amendment's right to privacy.", unit: "nixon", tag: "SCOTUS" },

    // ── Presidents & Vietnam ──
    { term: "Truman & Vietnam", definition: "Domino theory and containment developed under his administration. Provided $23 million to France to combat communist regime in Vietnam.", unit: "vietnam", tag: "Presidents" },
    { term: "Eisenhower & Vietnam", definition: "Provided support to French in Indochina War. After French defeat, gave financial aid to South Vietnam and sent 700 military advisors.", unit: "vietnam", tag: "Presidents" },
    { term: "JFK & Vietnam", definition: "Strong believer in containing communism and the Domino Theory. Increased military advisors to 16,000 by 1963.", unit: "vietnam", tag: "Presidents" },
    { term: "LBJ & Vietnam", definition: "Escalated the war using the Gulf of Tonkin Resolution. Troop levels grew from 16,700 to 500,000 by 1968.", unit: "vietnam", tag: "Presidents" },
    { term: "Nixon & Vietnam", definition: "Pursued 'Vietnamization' — turning the war over to South Vietnamese. Ended the draft but secretly bombed Cambodia. Resigned due to Watergate.", unit: "vietnam", tag: "Presidents" },
    { term: "Gerald Ford & Vietnam", definition: "Ordered the final evacuation of Vietnam in 1975. Saigon fell to North Vietnamese forces.", unit: "vietnam", tag: "Presidents" },
  ],

  // === Standard study data (same structure as philosophy) ===
  flashcards: [
    { prompt: "What was the Iron Curtain?", answer: "Churchill's metaphor for the dividing line between Soviet-controlled Eastern Europe and the democratic West, from his 1946 speech.", tag: "Cold War", chapter: "cold-war" },
    { prompt: "What was containment?", answer: "US foreign policy strategy from Kennan's Long Telegram to stop Soviet expansion by all means short of direct war.", tag: "Cold War", chapter: "cold-war" },
    { prompt: "What was the Truman Doctrine?", answer: "1947 policy that the US would support free peoples resisting subjugation. Gave $400M to Greece and Turkey.", tag: "Cold War", chapter: "cold-war" },
    { prompt: "What was the Marshall Plan?", answer: "US program of economic aid to rebuild Western Europe and prevent communist influence through alleviating poverty.", tag: "Cold War", chapter: "cold-war" },
    { prompt: "What was NATO?", answer: "North Atlantic Treaty Organization — mutual defense alliance where an attack on one member is considered an attack on all.", tag: "Cold War", chapter: "cold-war" },
    { prompt: "What was NSC-68?", answer: "1950 National Security Council report calling for massive military buildup to counter Soviet atomic threat.", tag: "Cold War", chapter: "cold-war" },
    { prompt: "What was Levittown?", answer: "Mass-produced suburban housing ($8,990-$16,500) built by William Levitt. Affordable but racially exclusionary — no homes sold to Black families.", tag: "Affluent Society", chapter: "affluent-society" },
    { prompt: "What was the Kitchen Debate?", answer: "1959 exchange between Nixon and Khrushchev arguing capitalism vs communism through consumer goods at a model American kitchen.", tag: "Affluent Society", chapter: "affluent-society" },
    { prompt: "What is de jure vs de facto segregation?", answer: "De jure = by law (South). De facto = by custom/practice without laws (North, especially housing discrimination).", tag: "Civil Rights", chapter: "civil-rights" },
    { prompt: "What was Brown v. Board of Education?", answer: "1954 Supreme Court ruling that 'separate educational facilities are inherently unequal,' overturning Plessy v. Ferguson.", tag: "Civil Rights", chapter: "civil-rights" },
    { prompt: "Who was Emmett Till?", answer: "14-year-old Black boy murdered in Mississippi in 1955. His mother's open-casket funeral galvanized the civil rights movement.", tag: "Civil Rights", chapter: "civil-rights" },
    { prompt: "What was the Montgomery Bus Boycott?", answer: "Year-long boycott (1955-56) sparked by Rosa Parks. Led by MLK; ended when Supreme Court declared bus segregation unconstitutional.", tag: "Civil Rights", chapter: "civil-rights" },
    { prompt: "Who were the Little Rock Nine?", answer: "Nine Black students who enrolled at Little Rock Central High in 1957. Protected by 101st Airborne after Governor Faubus blocked them.", tag: "Civil Rights", chapter: "civil-rights" },
    { prompt: "What was the Gulf of Tonkin Resolution?", answer: "1964 resolution giving the President unlimited authority to use force in Vietnam. Later revealed as based on exaggerated/fabricated attacks.", tag: "Vietnam", chapter: "vietnam" },
    { prompt: "What was the Tet Offensive?", answer: "1968 surprise attacks during Tet holiday. Military failure for communists but shattered US claims the war was being won.", tag: "Vietnam", chapter: "vietnam" },
    { prompt: "What was Vietnamization?", answer: "Nixon's policy of withdrawing US troops while transferring combat to South Vietnamese. Also ended the draft.", tag: "Vietnam", chapter: "vietnam" },
    { prompt: "What was the Silent Majority?", answer: "Nixon's term for Americans who supported the war and traditional values but didn't protest. From his November 1969 speech.", tag: "Nixon", chapter: "nixon" },
    { prompt: "What was the Southern Strategy?", answer: "Republican strategy to win Southern white voters by appealing to racial anxieties as Black voters registered as Democrats.", tag: "Nixon", chapter: "nixon" },
    { prompt: "What was Watergate?", answer: "1972 break-in at DNC headquarters and cover-up that led to Nixon's resignation in 1974 — the only presidential resignation in US history.", tag: "Nixon", chapter: "nixon" },
    { prompt: "What were the Stonewall Riots?", answer: "1969 police raid on a Greenwich Village gay bar sparked 5 days of rioting, launching the modern gay rights movement.", tag: "Nixon", chapter: "nixon" },
  ],

  quiz: [
    { question: "Who coined the term 'iron curtain' in a famous 1946 speech?", options: ["Harry Truman", "Winston Churchill", "George Kennan", "George Marshall"], answerIndex: 1, explanation: "Churchill used the phrase in his March 1946 speech: 'an iron curtain has descended across the continent.'", tag: "Cold War", chapter: "cold-war" },
    { question: "What did the Truman Doctrine specifically propose?", options: ["Military invasion of the Soviet Union", "$400 million in aid to Greece and Turkey", "A nuclear arms treaty", "Economic sanctions on Eastern Europe"], answerIndex: 1, explanation: "Truman asked Congress for $400M to support Greece and Turkey against communist pressure.", tag: "Cold War", chapter: "cold-war" },
    { question: "What was the main purpose of the Marshall Plan?", options: ["To build nuclear weapons", "To rebuild Western Europe economically", "To create a military alliance", "To contain communism in Asia"], answerIndex: 1, explanation: "The Marshall Plan provided economic aid to rebuild Europe and prevent the poverty that bred communism.", tag: "Cold War", chapter: "cold-war" },
    { question: "What did NATO establish?", options: ["Free trade zone", "Mutual defense — attack on one = attack on all", "Nuclear disarmament", "European parliament"], answerIndex: 1, explanation: "NATO's key principle: an armed attack against one member is considered an attack against all.", tag: "Cold War", chapter: "cold-war" },
    { question: "What was the significance of Plessy v. Ferguson (1896)?", options: ["Ended segregation", "Established 'separate but equal' as constitutional", "Desegregated the military", "Gave women the right to vote"], answerIndex: 1, explanation: "Plessy upheld 'separate but equal,' making segregated facilities legal for nearly 60 years.", tag: "Civil Rights", chapter: "civil-rights" },
    { question: "What did Brown v. Board of Education (1954) rule?", options: ["Segregation was constitutional if equal", "Separate educational facilities are inherently unequal", "Schools could choose their own policies", "Only federal schools must desegregate"], answerIndex: 1, explanation: "Brown overturned Plessy, declaring separate educational facilities inherently unequal.", tag: "Civil Rights", chapter: "civil-rights" },
    { question: "Who desegregated the US military with Executive Order 9981?", options: ["Eisenhower", "Truman", "Kennedy", "Roosevelt"], answerIndex: 1, explanation: "Truman issued Executive Order 9981 in 1948, influenced by A. Philip Randolph.", tag: "Civil Rights", chapter: "civil-rights" },
    { question: "Which organization was led by Martin Luther King Jr.?", options: ["NAACP", "CORE", "SNCC", "SCLC"], answerIndex: 3, explanation: "MLK led the Southern Christian Leadership Conference (SCLC) along with Ralph Abernathy.", tag: "Civil Rights", chapter: "civil-rights" },
    { question: "What triggered the Montgomery Bus Boycott?", options: ["Brown v. Board decision", "Emmett Till's murder", "Rosa Parks' arrest", "Little Rock Crisis"], answerIndex: 2, explanation: "Rosa Parks' arrest for refusing to give up her bus seat in 1955 sparked the year-long boycott.", tag: "Civil Rights", chapter: "civil-rights" },
    { question: "Who sent the 101st Airborne to protect the Little Rock Nine?", options: ["Truman", "Kennedy", "Eisenhower", "Johnson"], answerIndex: 2, explanation: "Eisenhower sent federal troops after Governor Faubus blocked Black students from entering the school.", tag: "Civil Rights", chapter: "civil-rights" },
    { question: "What was William Levitt's housing development known for?", options: ["Luxury homes for the wealthy", "Affordable mass-produced homes that excluded Black buyers", "Integrated communities", "Government-owned housing"], answerIndex: 1, explanation: "Levittown offered affordable homes but Levitt refused to sell to Black families.", tag: "Affluent Society", chapter: "affluent-society" },
    { question: "What did John Kenneth Galbraith criticize in The Affluent Society?", options: ["Military spending", "America prioritizing private wealth over public services", "Immigration policy", "Cold War diplomacy"], answerIndex: 1, explanation: "Galbraith argued America neglected public needs (schools, infrastructure) while celebrating private consumption.", tag: "Affluent Society", chapter: "affluent-society" },
    { question: "What did the Gulf of Tonkin Resolution authorize?", options: ["Diplomatic negotiations only", "Limited air strikes", "Unlimited presidential military authority in Vietnam", "A draft of 500,000 soldiers"], answerIndex: 2, explanation: "It gave the president full authority to deal with aggression in Vietnam — used to justify massive escalation.", tag: "Vietnam", chapter: "vietnam" },
    { question: "Which president escalated US troops in Vietnam from 16,700 to 500,000?", options: ["Kennedy", "Johnson", "Nixon", "Eisenhower"], answerIndex: 1, explanation: "LBJ massively escalated using the Gulf of Tonkin Resolution.", tag: "Vietnam", chapter: "vietnam" },
    { question: "What was the significance of the Tet Offensive?", options: ["US military victory that ended the war", "Communist military victory", "Turning point that shattered public confidence in the war", "Led to immediate US withdrawal"], answerIndex: 2, explanation: "Though a military failure for the communists, Tet destroyed US credibility about winning the war.", tag: "Vietnam", chapter: "vietnam" },
    { question: "What did the War Powers Act require?", options: ["Congressional approval before any military action", "President must inform Congress within 48 hours of deploying troops", "Automatic declaration of war after 30 days", "Senate approval of all military budgets"], answerIndex: 1, explanation: "The 1973 act required notification within 48 hours and set a 90-day limit without Congressional approval.", tag: "Vietnam", chapter: "vietnam" },
    { question: "What was Nixon's 'Southern Strategy'?", options: ["Withdrawing troops from the South", "Winning Southern white voters through racial appeals", "Building military bases in the South", "Supporting Southern civil rights"], answerIndex: 1, explanation: "Nixon strategist Kevin Phillips openly described winning white voters as Black voters joined the Democrats.", tag: "Nixon", chapter: "nixon" },
    { question: "What event launched the modern gay rights movement?", options: ["March on Washington", "Stonewall Riots", "Occupation of Alcatraz", "ERA campaign"], answerIndex: 1, explanation: "The 1969 police raid on the Stonewall Inn sparked 5 days of rioting and launched gay pride movements.", tag: "Nixon", chapter: "nixon" },
    { question: "What did Miranda v. Arizona (1966) establish?", options: ["Freedom of the press", "Right to privacy", "Rights of the accused must be read upon arrest", "School desegregation"], answerIndex: 2, explanation: "Miranda established that suspects must be informed of their rights — the 'Miranda rights.'", tag: "SCOTUS", chapter: "civil-rights" },
    { question: "What did Tinker v. Des Moines (1969) establish?", options: ["Students can be expelled for protests", "Students retain free speech rights at school", "Schools can ban political symbols", "Teachers have no free speech"], answerIndex: 1, explanation: "The Court ruled students don't 'shed their constitutional rights at the schoolhouse gate.'", tag: "SCOTUS", chapter: "civil-rights" },
  ],

  shortAnswers: [
    { prompt: "Explain how containment shaped US foreign policy from 1947 to 1950.", include: ["Kennan's Long Telegram recommended containing Soviet expansion", "Truman Doctrine committed US to supporting free peoples — $400M to Greece/Turkey", "Marshall Plan used economic aid to rebuild Europe and prevent communism", "NSC-68 called for massive military buildup against Soviet atomic threat", "NATO created mutual defense alliance in Western Europe"], chapter: "cold-war" },
    { prompt: "How was the Cold War fought without direct military conflict between the US and USSR?", include: ["Economic aid (Marshall Plan) to prevent communism", "Military alliances (NATO vs Warsaw Pact)", "Proxy conflicts and support for allied nations", "Propaganda and ideological competition (Kitchen Debate)", "Nuclear arms race and deterrence", "Berlin Airlift showed Western resolve without shooting"], chapter: "cold-war" },
    { prompt: "Was the 1950s truly an 'affluent society'? Explain who benefited and who was left out.", include: ["Suburbanization and consumer culture created prosperity for white middle class", "Levittown excluded Black families — housing discrimination", "Harrington's Other America exposed 40-50 million in poverty", "Galbraith criticized prioritizing private wealth over public services", "Gender roles confined women to domestic sphere", "Beat Generation rejected conformity"], chapter: "affluent-society" },
    { prompt: "Explain the legal strategy of the civil rights movement from Plessy to Brown.", include: ["Plessy v. Ferguson (1896) established 'separate but equal'", "NAACP used legal challenges to attack segregation", "Thurgood Marshall argued Brown v. Board before the Supreme Court", "Brown (1954) declared separate educational facilities inherently unequal", "Brown II ordered desegregation 'with all deliberate speed' — very slow in practice"], chapter: "civil-rights" },
    { prompt: "How did nonviolent protest advance the civil rights movement?", include: ["Montgomery Bus Boycott lasted a year, ended bus segregation", "Sit-ins at lunch counters spread rapidly", "Freedom Riders tested desegregation rulings", "MLK's Letter from Birmingham Jail defended civil disobedience", "March on Washington brought 250,000+ people", "Television made protesters look peaceful and opponents look violent"], chapter: "civil-rights" },
    { prompt: "Explain why the Vietnam War became increasingly unpopular in the United States.", include: ["Gulf of Tonkin Resolution based on exaggerated/fabricated attacks", "Massive escalation under LBJ — 500,000 troops", "Tet Offensive shattered claims the war was being won", "Pentagon Papers revealed government deception", "Draft disproportionately affected poor and minorities", "Counterculture movement and anti-war protests", "Media coverage brought war's brutality into American homes"], chapter: "vietnam" },
    { prompt: "Describe the role of each president in the Vietnam War.", include: ["Truman: containment theory, $23M to France", "Eisenhower: supported French, sent 700 advisors", "JFK: increased advisors to 16,000", "LBJ: escalated to 500,000 troops using Gulf of Tonkin", "Nixon: Vietnamization, ended draft, bombed Cambodia, Watergate", "Ford: ordered final evacuation"], chapter: "vietnam" },
    { prompt: "How did the 'Rights Revolution' of the 1960s extend beyond African Americans?", include: ["Women's movement — Friedan's Feminine Mystique, NOW, ERA", "Gay rights — Stonewall Riots 1969 launched pride movement", "Latino rights — Chicano movement, Cesar Chavez and United Farm Workers", "Native American rights — AIM (1968), Occupation of Alcatraz (1969)", "Environmental movement — Rachel Carson's Silent Spring", "SCOTUS expanded rights: privacy, free speech, due process"], chapter: "nixon" },
    { prompt: "How did Nixon represent a 'conservative turn' in American politics?", include: ["Silent Majority speech appealed to traditional values", "Southern Strategy used racial anxiety to win white Southern voters", "Opposed counterculture and anti-war movement", "YAF and Sharon Statement represented conservative youth", "Despite conservative rhetoric, created EPA and opened relations with China", "Watergate destroyed public trust in government"], chapter: "nixon" },
  ],

  matchingSets: [
    { title: "Cold War Documents & Their Authors", chapter: "cold-war", pairs: [
      { term: "Iron Curtain Speech", definition: "Winston Churchill (1946)" },
      { term: "Long Telegram", definition: "George Kennan (1946)" },
      { term: "Truman Doctrine Speech", definition: "President Truman (1947)" },
      { term: "Harvard Speech on European Aid", definition: "George Marshall (1947)" },
      { term: "NSC-68", definition: "National Security Council (1950)" },
      { term: "Critique of Containment", definition: "Walter Lippmann (1947)" },
    ]},
    { title: "Civil Rights Organizations & Leaders", chapter: "civil-rights", pairs: [
      { term: "NAACP", definition: "W.E.B. DuBois and Ida Wells" },
      { term: "CORE", definition: "James Farmer and Bayard Rustin" },
      { term: "SNCC", definition: "Ella Baker" },
      { term: "SCLC", definition: "Martin Luther King Jr." },
    ]},
    { title: "Supreme Court Cases & Rulings", chapter: "civil-rights", pairs: [
      { term: "Engel v. Vitale (1962)", definition: "No mandatory prayer in schools — 1st Amendment" },
      { term: "Griswold v. Connecticut (1965)", definition: "Right to privacy / contraception" },
      { term: "Miranda v. Arizona (1966)", definition: "Rights of the accused — 5th Amendment" },
      { term: "Loving v. Virginia (1967)", definition: "Interracial marriage protected — 14th Amendment" },
      { term: "Tinker v. Des Moines (1969)", definition: "Students retain free speech at school — 1st Amendment" },
      { term: "Roe v. Wade (1973)", definition: "Abortion is constitutional right — 14th Amendment" },
    ]},
    { title: "Civil Rights Tactics & Examples", chapter: "civil-rights", pairs: [
      { term: "Boycotts", definition: "Montgomery Bus Boycott (1955-56)" },
      { term: "Sit-ins", definition: "Greensboro lunch counter protests (1960)" },
      { term: "Freedom Rides", definition: "Testing desegregation on interstate buses" },
      { term: "Legal action", definition: "Brown v. Board argued by Thurgood Marshall" },
      { term: "Mass demonstrations", definition: "March on Washington (1963)" },
    ]},
    { title: "Presidents & Vietnam Involvement", chapter: "vietnam", pairs: [
      { term: "Truman", definition: "$23M to France, containment theory" },
      { term: "Eisenhower", definition: "700 advisors, supported French" },
      { term: "Kennedy", definition: "16,000 advisors, Domino Theory" },
      { term: "Johnson", definition: "500,000 troops, Gulf of Tonkin" },
      { term: "Nixon", definition: "Vietnamization, bombed Cambodia" },
      { term: "Ford", definition: "Final evacuation of Vietnam" },
    ]},
    { title: "Rights Movements of the 1960s-70s", chapter: "nixon", pairs: [
      { term: "Women's Movement", definition: "Betty Friedan, NOW, ERA" },
      { term: "Gay Rights", definition: "Stonewall Riots (1969)" },
      { term: "Chicano Movement", definition: "Cesar Chavez, United Farm Workers" },
      { term: "Native American Rights", definition: "AIM, Occupation of Alcatraz" },
      { term: "Environmentalism", definition: "Rachel Carson, Silent Spring" },
    ]},
  ],

  comparisons: [
    { title: "Containment vs Isolationism", summary: "Containment actively engaged the world to stop communism; isolationism would have avoided foreign entanglements entirely.", whyItMatters: "Containment committed the US to decades of Cold War interventions from Europe to Vietnam.", chapter: "cold-war" },
    { title: "NATO vs Warsaw Pact", summary: "NATO united the West in mutual defense; the Warsaw Pact was the Soviet counter-alliance. Together they formalized the Cold War's two-bloc system.", whyItMatters: "Created the military framework for Cold War confrontation and made Europe a potential nuclear battlefield.", chapter: "cold-war" },
    { title: "De jure vs De facto Segregation", summary: "De jure segregation was enforced by law (South); de facto segregation existed through custom and housing discrimination (North).", whyItMatters: "Civil rights legislation could end de jure segregation but de facto segregation proved much harder to dismantle.", chapter: "civil-rights" },
    { title: "Plessy v. Ferguson vs Brown v. Board", summary: "Plessy (1896) upheld 'separate but equal'; Brown (1954) declared separate facilities inherently unequal.", whyItMatters: "Brown overturned 58 years of legal segregation but 'with all deliberate speed' meant change was painfully slow.", chapter: "civil-rights" },
    { title: "MLK's Nonviolence vs Malcolm X / Black Power", summary: "MLK advocated nonviolent civil disobedience influenced by Gandhi; Malcolm X and Black Power emphasized self-defense and Black pride.", whyItMatters: "Shows the movement wasn't monolithic — different strategies reflected different experiences and goals.", chapter: "civil-rights" },
    { title: "Affluent America vs The Other America", summary: "Suburban prosperity existed alongside 40-50 million Americans in poverty. Galbraith and Harrington exposed this contradiction.", whyItMatters: "The 'affluent society' label hid massive inequality. Harrington's book influenced LBJ's War on Poverty.", chapter: "affluent-society" },
    { title: "Conformity vs Beat Generation", summary: "1950s mainstream culture valued suburban conformity; Beats (Ginsberg, Kerouac) rejected materialism and social norms.", whyItMatters: "The Beats were precursors to the 1960s counterculture that challenged the entire system.", chapter: "affluent-society" },
    { title: "Hawks vs Doves (Vietnam)", summary: "Hawks supported escalation and military victory; Doves wanted negotiation and withdrawal.", whyItMatters: "This division tore American society apart and reshaped politics for decades.", chapter: "vietnam" },
    { title: "Counterculture vs Conservative Turn", summary: "1960s counterculture challenged authority and tradition; simultaneously, a conservative movement (YAF, Silent Majority) pushed back.", whyItMatters: "Nixon's election showed the conservative backlash was politically powerful — reshaping the Republican Party.", chapter: "nixon" },
    { title: "Nixon's Contradictions", summary: "Nixon appealed to conservatives but created the EPA and opened relations with China. He pursued détente while secretly bombing Cambodia.", whyItMatters: "Shows how presidents can't be simply categorized; Watergate ultimately destroyed his legacy.", chapter: "nixon" },
  ],

  overview: {
    chapterMap: [
      { chapter: "Cold War", points: [
        "Post-WWII alliance breakdown between US and USSR",
        "Containment strategy from Kennan's Long Telegram shaped decades of policy",
        "Truman Doctrine, Marshall Plan, NATO built the Western alliance",
        "NSC-68 called for massive military buildup",
        "Berlin Airlift showed resolve without direct conflict",
        "Nuclear arms race created existential anxiety (Duck and Cover)",
      ]},
      { chapter: "Affluent Society", points: [
        "Suburbanization, consumer culture, and conformity defined the 1950s",
        "Levittown: affordable housing but racially exclusionary",
        "Kitchen Debate: capitalism vs communism through consumer goods",
        "Galbraith criticized private wealth over public services",
        "Harrington exposed 40-50 million in hidden poverty",
        "Beat Generation rejected conformity and materialism",
      ]},
      { chapter: "Civil Rights", points: [
        "Plessy (1896) legalized segregation; Brown (1954) overturned it",
        "Key tactics: boycotts, sit-ins, Freedom Rides, legal action, marches",
        "Key figures: MLK, Rosa Parks, Thurgood Marshall, Ella Baker",
        "Key organizations: NAACP, CORE, SNCC, SCLC",
        "TV made nonviolent protesters sympathetic and opponents look violent",
        "Civil Rights Act (1964) and Voting Rights Act (1965) were landmark legislation",
      ]},
      { chapter: "Vietnam War", points: [
        "Rooted in containment and Domino Theory",
        "Gulf of Tonkin Resolution gave president unlimited war authority",
        "Escalation under LBJ: 16,700 to 500,000 troops",
        "Tet Offensive (1968) shattered public confidence",
        "Nixon's Vietnamization withdrew troops but bombed Cambodia",
        "58,000 Americans and 2+ million Vietnamese died",
        "War Powers Act (1973) limited presidential military power",
      ]},
      { chapter: "Nixon & Conservative Turn", points: [
        "Rights Revolution: women, gay, Latino, Native American, environmental movements",
        "Conservative backlash: YAF, Sharon Statement, Silent Majority",
        "Nixon's Southern Strategy realigned party politics",
        "Détente eased Cold War tensions; opened China relations",
        "Watergate scandal destroyed public trust; Nixon resigned 1974",
        "Stagflation defined the economic crisis of the 1970s",
      ]},
    ],
    likelyQuestions: [
      "How was the Cold War fought without direct US-Soviet military conflict?",
      "Was the 1950s truly an 'affluent society'? Who benefited and who was left out?",
      "Trace the legal strategy from Plessy to Brown.",
      "How did nonviolent protest advance civil rights?",
      "Why did Vietnam become increasingly unpopular?",
      "How did Nixon represent a conservative turn?",
      "Compare the roles of different presidents in Vietnam.",
      "How did the Rights Revolution extend beyond African Americans?",
    ],
    cramChecklist: [
      "Iron Curtain → Containment → Truman Doctrine → Marshall Plan → NATO",
      "Plessy (separate but equal) → Brown (inherently unequal) → Civil Rights Act → Voting Rights Act",
      "De jure (by law, South) vs de facto (by custom, North)",
      "NAACP (legal) → SCLC (MLK) → SNCC (students) → CORE (direct action)",
      "Tonkin Resolution → Rolling Thunder → Tet Offensive → Vietnamization → War Powers Act",
      "Truman → Eisenhower → JFK → LBJ → Nixon → Ford (each president escalated then withdrew)",
      "Counterculture vs Conservative Turn → Nixon's Silent Majority",
      "SCOTUS: Engel, Baker, Griswold, Miranda, Sullivan, Loving, Tinker, Roe",
    ],
  },
};
